### ISSUE TITLE
uploader TODO

### ISSUE THREAD

**Issue by wolfbiter** [linxmix/linx#365]
## Priority
- [x] implement play buttons to play... 10sec before switch?
- [x] implement special load functionality for transitions
  - if transition already existing, load correct start/end songs with in/out regions on all waves
- [x] implement special save functionality for transition
  - save on in/out position change
  - be a red warning color if they're start and endSong are different than already saved with
    - or maybe save as new transition object in my DB, pointing to same file in backend?
  - update `hasIssue` on `transition` model on save
  - make sure that mixPoints save correctly. need to link new id's once they are persisted

## Todo
- [x] call compareWaves on region-update-end / region created
- [x] figure out migrations - from previous transitions to mixPoints
- [x] implement migration: track._id to s3FileName
  - [x] after above migration, rewrite `TrackModel.getS3Url`
- [x] implement migration: `track.dj` to `track.createdBy`
- [x] cancel uploading/analyzing/loading on wave reset
  - change `reset` button to `cancel` when uploading or analyzing or w/e
  - can't always actually cancel - that's fine, just hide loading bar and what not
- [x] implement `linxSearchParams`

## Done
- [x] finish TODO's in WaveSurfer
- [x] finish soundcloudinput URL validation
- [x] finish search linx dropdown
  - for transitions or songs
  - modal?
- [x] make soundcloudUrl input 100% width
- [x] figure out drop segment height
- [x] get a true center on song title/artist
- [x] handle 404/etc error gracefully on wave.load
- [x] hide upload options while loading a wave

- [x] move upload edit functions into upload wave (ie `empty`, `upload`)
- [x] move upload edit functions to uploadWaveControls
- [x] implement `upload`
  * [x] click to get song analyzed in echonest (based on `wave.meta.getMeta('type')`)
  * [x] depressed with check mark if already done
  * [x] loading screen with %'s while loading
  * [x] finish work in`UploadWaveControls`
- [x] debug `LinxModel.getMongoAttributes()`
- [x] debug `StupidModel.persist()`
  - [x] display uploading status on `uploadwavecontrols`
  - [x] implement `TrackModel.setEchonest`
  - [x] implement `WaveSurfer.getEchonestAnalysis`
  - [x] implement `WaveSurfer.getEchonestId`
  - [x] implement multiple tries on `WaveSurfer.getEchonestAnaylsis`
- [x] finish calculating S3 factor
  - [x] implement `WaveSurfer._uploadToS3`
- [x] debug track.s3FileName not getting set on upload to s3

* [x] setup smooth error handling on entire function so that user gets alerted
  - maybe something like a wrapping try-catch?

- [x] make my error handler only proc once per error
- [x] convert to using semantic progress module to show percent on loading bar
