### ISSUE TITLE
mixlist TODO

### ISSUE THREAD

**Issue by wolfbiter** [linxmix/linx#367]
leftover TODOs

- [ ]  fix mix edit info modal name (edit on edit, create on create)
- [ ] fix mixlist not rerendering on song change
- [ ] fix scrolling in mixlist
- [ ] make mixboxes checkboxes colored
- [ ] auto scroll mixlist when new song is selected
- [ ] finish filtering and other users in sidebar
- [ ] add `createdBy` to `Mix` model
- [ ] ability to search transitions to add to mixlist
