### ISSUE TITLE
Uploader v1 TODO

### ISSUE THREAD

**Issue by wolfbiter** [linxmix/linx#373]
## Steps
- [x] make sure refresh is actually reactive.
  - is it TOO reactive? don't want to depend on every trait in model...
- [x] make sure links and mixes get stored when they are saved
- [x] rewrite get to auto do refresh. make all models reactive to DB.
  - unless `model.isNew`
  - add `Model.store()`, which clears `isNew`.
- [x] remove old regions in drawRegions
- [x] reimplement track analysis, profile, compare
  - move to wave
  - store echonest analysis in same way as wavesurfers
- [x] figure out how to handle rendering wave in multiple places (currently the case)
- [x] debug getWaves not updating for mix page when adding/removing tracks
- [x] debug track link modal waves not being linked
- [x] make Model.get use refresh()?
  - so that ex playing waves will get their play status update
- [x] debug getLinkData returning wrong for addTrack index
- [x] link / unlink icon when link exists / doesnt exist
- [x] implement track links list

## Short-Term
- [x] figure out wave multi-loads
  - ie analyzing and loading on add track link modal open
- [x] figure out TODO's in wave.loadFiles
  - source recently uploaded tracks from locally stored files
- [x] figure out new track / new mix, no _id
  - could maybe assume everything is new with _id, then clean up orphans?
  - similar issue in making links for regions
- [x] fix drop zone dropness
- [x] add drag and drop file picker button to drop zone
- [x] set volume based on echoNest analysis gain, and replay gain algorithm
- [x] abstract mixPoints in such a way that you can do it for startSong and endSong both
  * do this while thinking beyond just a single transition
- [x] add default case in drawMixPoints to generate most unique colors:
  * http://stackoverflow.com/questions/6823286/create-unique-colors-using-javascript
- [x] set `playing` to false when track ends
- [x] when creating a model, auto-set `createdBy` field to currentUser
- [x] debug loading bars sharing state on upload to s3
  * has to do with tracker?
  * is this a confirmed bug? or was i just impatient? check network tab
- [x] figure out what meteor package to use for semantic. need v1.11.0.
  - [x] after this, debug loading bar percent going to 0 if it isn't fixed by updating
  - [x] after this, also give transitions new title for search
  - [x] figure out how to cache a track that was just uploaded (so dont have to reload)
- [x] make better solution to loading situation
