### ISSUE TITLE
Add Tracks TODO

### ISSUE THREAD

**Issue by wolfbiter** [linxmix/linx#385]
## Necessary
- [x] fix chain and compose
- [x] figure out currentItem, total, length, etc for power queue
- [x] flesh out loading modal
- [x] make sure loading modal gets 
- [x] fix multi file drop and save
- [x] move loading logic out of track, represent in relevant template - ie addLinksModal.
  - clean from uploadToS3
- [x] don't block ui for loading md5
- [x] think about how to catch multiple of same track in add tracks modal
- [x] do `window.confirm` on `window.onbeforeunload` whenever file(s) are uploading
- [x] figure out save tracks button, have bug with clicking closes modal
- [x] move wave uploading logic and `wave.saveBackend` to track. have wave observe track's loading state, and update that in template
  - make track show progress bar for loading audio files
- [x] update track accordion, move mixpage-specific logic out. use track accordions in track uploader
 - verify it fix waves reloading when one is removed [only tracks after the one removed reload... hmmm...]
 - or maybe dont use track accordion... hmmm...
- [x] Auto - link button which puts Spinner and adds links to tracks that don't have them
- [x] short-circuit upload step for tracks that echonest already has, which means calc md5 and check for existing
  - see old linx code with spark md5
- [x] handle wave upload errors gracefully (ie allow reset)
 - might actually have to serialize uploads
- [x] create cancel upload function(?)
  - call when wave is reset (?), call when track is removed from add_track_modal

**things to think about
- wave accordion sizes. slider to change? preset sizes?
- wavesurfer timeline, spectrogram, minimap

## Fun
- [ ] color waves based on track type
- [ ] show key bpm etc info in track
- [ ] release region drag on mouseUp anywhere on page
- [ ] marker on wave hover
- [ ] get meteor logging going

## Long-Term
- [x] eventually replace lepozepo:s3 with my own implementation
- [x] short-circuit upload step for tracks that echonest already has, which means calc md5 and check for existing
- [ ] make echonest analysis wait time (both loading bar and xhr reattempt timeout) depend on `bufferLength`
- [ ] add meteor-trail to get client logs in server
- [x] make `Model.get()` reactive without requiring `this.refresh()`
- [ ] adding another mix to your mix?

**Comment by wolfbiter** [comment]
Move progress bar and functions into own template component. Use that in wave. Make add tracks open up a second modal which indicates saving, use progress bar (?) And serially upload tracks while observing track loading progress.

**Comment by wolfbiter** [comment]
Show 'new" next to new tracks

Use loading modal for add links button. Think about abstracting that - serial loading with progress meters
