### ISSUE TITLE
MVP TODO

### ISSUE THREAD

**Issue by wolfbiter** [linxmix/linx#388]
## Necessary
- [ ] improve algorithm [ a good investment regardless ]
- [x] don't alert on wave error
- [ ] add optional additional progress bar to upload files that shows progress of current file upload
- [x] don't have two loading bars in track wave
- [ ] make loading modal closeable ?
- [ ] implement choose files, fix drag n drop text
- [ ] ability to specify track as "mix" or "transition"
- [ ] fix waves scrolling
- [ ] `play mix` button
- [ ] dropping tracks on mix page opens tracks modal
- [ ] database cleaning functions
- [ ] track page, for deleting track, seeing whose it is, and editing file. can also easily list links.
 - note: need to remove track from mixes that have track. window.confirm
- [ ] need to be able to save/download mix as file
 - https://github.com/mattdiamond/Recorderjs
- [x] fix bug with not being able to play track that tried to play a track that couldnt
- [ ] remove links when removing/changing tracks in a mix

### Errors
- [ ] think of good way to handle inevitable network errors, eg "try again. if persists, contact wolfbiter@gmail.com"
  - ie echonest analyzer is being slow
  - if analyzer fails a lot, try restarting with track upload
  - can maybe just keep going and skip that one?
- [ ] at end of power queue, show users names of unsuccessful items
 - maybe use PowerQueue.errorHandler(data, addTask, failures)

### performance
- [ ] remove track loading - ex don't set percent for tracks in server
 - move into loading item, use that to power trackLoading progress. also do for file upload in upload.js - make progress bar listen to a loading item
- [ ] separate clicking on accordion from getElementdata
  - somehow, since they're slow to open in long mixes
- [ ] somehow make tracks not reload when removing a track
  - both in modal and mixpage

## Fun
- [ ] playMix button
- [ ] volume slider
- [ ] drag and drop
- [ ] color waves based on track type
- [ ] show key bpm etc info in track
- [ ] release region drag on mouseUp anywhere on page
- [ ] marker on wave hover
- [ ] get meteor logging going

**things to think about
- wave accordion sizes. slider to change? preset sizes?
- wavesurfer timeline, spectrogram, minimap
